version: '3'
services:
  server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - AI_API_KEY=${AI_API_KEY}
      - NODE_ENV=production
    volumes:
      - ..:/app
    command: >
      sh -c "pnpm nx run server:test &&
             pnpm nx run server:start"
    deploy:
      replicas: 1

  client:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - '3030:3030'
    environment:
      - NODE_ENV=production
    volumes:
      - ..:/app
    command: >
      sh -c "pnpm nx run client:start"
    deploy:
      replicas: 1
